### ISSUE TITLE
Huge mistake in Identifier.py in branch base-gender

### ISSUE THREAD

**Issue by dinhanhx** [huonglarne/speaker-recognition#1]
https://github.com/huonglarne/speaker-recognition/blob/4a3e7384c439a9c891ea4fc7e5b778f47454a937/Identifier.py#L33-L42

`best_score` shoulde be `-inf` to find negative value since `gmm.score()` return `log(prob)`

Also use `max()` please

**Comment by huonglarne** [comment]
thanks a lot. will fix as soon as possible.

**Comment by huonglarne** [comment]
Issue fixed.
