### ISSUE TITLE
Lack of enrichment in features.py in branch china-number-1

### ISSUE THREAD

**Issue by dinhanhx** [huonglarne/speaker-recognition#2]
https://github.com/huonglarne/speaker-recognition/blob/331cd3f86f0ae459435b0a639c4396ff187db40e/features.py#L4-L8
Please implement `delta()` from `python_speech_extraction` to improve quality

**Comment by huonglarne** [comment]
actually i am going to report about the difference between mfcc with and without delta. @9a24f0 @PhuongPhg  your choice. you can look into my code, file features_extraction.py to see the integration of delta to mfcc.

**Comment by PhuongPhg** [comment]
I have added `delta` and the chances of recognizing my voice went down to 60% ... 😢

**Comment by dinhanhx** [comment]
@PhuongPhg  Try one more times delta() to make mfcc+d+dd

**Comment by 9a24f0** [comment]
please elaborate why we must include `delta()`. Since when we include delta, the score decrease...

**Comment by dinhanhx** [comment]
@9a24f0 and @PhuongPhg  Read this [citation](https://www.researchgate.net/post/What_would_be_better_features_MFCC_or_MFCC_delta_deltadelta_in_speaker_recogntion/572752fd217e20094d7ed760/citation/download).
